apiVersion: apps/v1
kind: deployment
metadata:
  name: ms-prueba-app 
  labels:
    app: ms-prueba-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-prueba-app
  template:
    metadata:
      labels:
        app: ms-prueba-app
    spec:
      containers:
        - name: ms-prueba-app
          image: ms-prueba-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /metrics
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "100m"  