version: '3.8'

services:
  jenkins:
    build: .
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-local
    restart: unless-stopped
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - C:\Users\welicona\.ssh:/var/jenkins_home/.ssh:rw
    extra_hosts:
      - "kubernetes.docker.internal:host-gateway"
      - "host.docker.internal:host-gateway"  
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--prefix=/jenkins
    networks:
      - jenkins-net

volumes:
  jenkins_home: {}

networks:
  jenkins-net:
    driver: bridge
